package com.linjson.flatbuffers;

// automatically generated by the FlatBuffers compiler, do not modify

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Car extends Table {
  public static Car getRootAsCar(ByteBuffer _bb) { return getRootAsCar(_bb, new Car()); }
  public static Car getRootAsCar(ByteBuffer _bb, Car obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public Car __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public String name() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public String color() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer colorAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }

  public static int createCar(FlatBufferBuilder builder,
      int nameOffset,
      int colorOffset) {
    builder.startObject(2);
    Car.addColor(builder, colorOffset);
    Car.addName(builder, nameOffset);
    return Car.endCar(builder);
  }

  public static void startCar(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(0, nameOffset, 0); }
  public static void addColor(FlatBufferBuilder builder, int colorOffset) { builder.addOffset(1, colorOffset, 0); }
  public static int endCar(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishCarBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
};

